language: java
install: true

jdk:
  - oraclejdk8

addons:
  sonarcloud:
    organization: "sudiamanj-github"
    token:
      secure: "Y6XEEjApWqfcNm6dD4O+vaUwzo4bbMMw+E/jDVLWw7Lo0KhBF1BZQ3spQ6PvaAzB9/JshojpQAptU66vGmk8HHK2VuIV0EJOF1AHBbsqutkWA7rzEclSVGpO/IP90UzU88Vq310G/y+JNhylMro5bgmVoX81i9lKpmiRg7yGyDE1QCtUartjhLFoJ/uZBco6FD3QZP4dXdUi7Uuf/E9kE7OsAuPPvIwF6ruQzu4whlyAb96eqjOsfXt8fOyxLySboRU0HWKzi+AboX+0S6xCZ2JK6zeI5PbO6YYDnzqhHEw/lRIyt9UWyJkc161GLS7YiIr2JlYZkLznbu2WMPKYm8DISJJzml+mtIZWO6xbmBg7SdXRJDBAsZBEgjYa2a2NsJt+LTEau+FQ6SaNKLWeFa8gljqNiM50LUP3MsO6RCwyf7ea5OEgOWv3MpIQhpS1xT0zS0ab+dRoqjf9JuX6Ia5zZcldvli7SFgGw+yrJJ4yggYOZchYkFVTZKtg4odOEEMV3Bo1NrQoqYVz9XcY2Xmo+KMsrjNjAML8/brnRRZAMXXYHo1yLVg7nJyrChtaWeXCTIugp2aHAwmPSxhe4wbOHts61zg66vfJUBHgTX8/jbCtLytmuD7lljhVpYetdUXy7IPbk1Bs5uKYzRUr2/gfdkgGG83wDaetqvcmapY="

script:
  - ./gradlew sonarqube fatJar
  - cp build/libs/C-na-all.jar Cna.jar
